#端口配置
server:
  port: 80
  servlet:
    context-path: /

#spring datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db40?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    prefix: classpath:/templates/
    suffix: .html

#spring mybatis

#mybatis:
#  configuration:
#    default-statement-timeout: 30
#    map-underscore-to-camel-case: true #开启驼峰映射
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.vy.common.pojo
#mybatis-plus
mybatis-plus:
  type-aliases-package: com.vy.common.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#spring mvc